### ISSUE TITLE
Ajout d’un `mtm_campaign` pour l’API de recherche d’entreprises

### ISSUE THREAD

**Issue by XavierJp** [betagouv/portail-rse#90]
Nous souhaiterions tracker plus finement les utilisations de notre API Recherche d’Entreprises. Pourriez-vous ajouter `mtm_campaign=portail-rse` à la fin de l’url ?

https://github.com/betagouv/portail-rse/blob/84abe017f9e39422be9a36fe9d17139f925b9172/doc/homologation/diagramme_cas_utilisation.plantuml#L4

Les stats apparaitront ici dans la partie `Campagne` :
https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=294&period=range&date=previous30#?period=day&date=2024-04-30&idSite=294&category=Referrers_Referrers&subcategory=Referrers_WidgetGetAll

**Comment by sblondon** [comment]
Oui, pas de problème pour ajouter ce paramètre à nos requêtes.

Nous vous dirons quand c'est en production.

**Comment by XavierJp** [comment]
Merci beaucoup !

**Comment by sblondon** [comment]
Les visites d'hier ne sont pas visibles, ce qui est bizarre.

Le paramètre est passé en production ; cela devrait permettre d'avoir plus de requêtes sur l'API.

Je ne clos pas tant qu'on ne voit pas les visites sur matomo.

**Comment by sblondon** [comment]
Je pense que j'ai compris le problème: nous faisons la requête côté serveur donc il n'y a pas de requête sortante vers matomo puisque cela est fait par le code js de matomo dans le front. Il faudrait avoir une autre solution (envoyer une requête vers matomo en parallèle, récupérer la requête de votre côté, etc.).

**Comment by XavierJp** [comment]
Bonjour @sblondon,

L'endroit d'où est originaire la requete (serveur ou client) n'a pas d'importance. 

L'appel a matomo se fait chez nous. Notre serveur recoit votre requete et la log dans matomo.

Attention, pour ne pas épuiser matomo, nous ne loggons que 1% des requêtes. Donc si vous faites moins de 100 requetes dans la journée, c'est possible que vos requêtes n'apparaissent pas. Si c'est bien cela, elles apparaitrons dans le mois. 

Ces chiffres sont donc à mutliplier par 100 : 
https://stats.data.gouv.fr/index.php?module=CoreHome&action=index&idSite=294&period=range&date=previous30#?period=range&date=2024-05-06,2024-05-08&idSite=294&category=Referrers_Referrers&subcategory=Referrers_WidgetGetAll
<img width="746" alt="image" src="https://github.com/betagouv/portail-rse/assets/8900205/1314a471-3cdf-4925-a179-7f9d1cd7e072">

**Comment by XavierJp** [comment]
Je ne vois pas d'erreur dans le code https://github.com/betagouv/portail-rse/commit/cc0d0317348f9e7881aa41e37e54d9dcbe620ef2

Donc je penche pour mon explication plus haut. Est ce que tu as une estimation du volume de requêtes que vous faites ?

**Comment by sblondon** [comment]
`portail-rse` est bien visible maintenant sur matomo. Je clos donc le ticket.

**Comment by XavierJp** [comment]
Superbe !
